### PR TITLE
fix: prevent INJECT_DEBUG js script multiple execution

### LINKED ISSUE #99: Webview console output printed multiple times
When creating Webview component with `debug: true`, at some point the same console output was printed multiple times.

Image

This problem seems to occur when INJECT_DEBUG is injected multiple times.

I don't know why this is happening, but I think this can be solved by adding a guard condition to the code that will be injected that will only be executed once, like below.
```typescript
// in ./packages/react-native/integration/console.ts
export const INJECT_DEBUG = `
{
  if (!window.debugInjected) {
    window.debugInjected = true;
// ...
```

This is one of the simplest ways to know if a script has already been injected, but we think there could be a better approach.

### PR DESCRIPTION
**Pull request by wogns3623**
FIx #99

I tested it locally but not sure there aren't potential issue

### CODE REVIEW

File: packages/react-native/src/integrations/console.ts [hunk 1]
```diff
@@ -1,32 +1,35 @@
 export const INJECT_DEBUG = `
 {
-  const originalConsoleLog = console.log;
-  const originalConsoleError = console.error;
-  const originalConsoleWarn = console.warn;
+  if (!window["webview_bridge_debug_injected"]) {
```
Comment (gronxb) [inline packages/react-native/src/integrations/console.ts:3]:
```suggestion
  if (window["webview_bridge_debug_injected"]) {
    return;
  }
```

how about use early return  ?

**Review by gronxb — CHANGES_REQUESTED** [review]

File: packages/react-native/src/integrations/console.ts (hunk 1 above)
Comment (gronxb) [reply packages/react-native/src/integrations/console.ts:3]: and It’s a minor detail, but as shown above, generating a random value and using it can be a good idea.
Although the possibility is low, storing it on the window object can cause name collisions.

 ```ts
import { createRandomId } from "@webview-bridge/utils";

const randomId = createRandomId();

export const INJECT_DEBUG = `
{
  const originalConsoleLog = console.log;
  const originalConsoleError = console.error;
  const originalConsoleWarn = console.warn;
  if (!window["webview_bridge_debug_injected_${randomId}"]) { // <<
```

Comment (wogns3623) [reply packages/react-native/src/integrations/console.ts:3]: > Although the possibility is low, storing it on the window object can cause name collisions.

I was worried about naming collisions too, but couldn't think of a way around it.
This seems like the perfect solution.

Comment (wogns3623) [reply packages/react-native/src/integrations/console.ts:3]: What do you think about prefix `webview_bridge_debug_injected_`?
If there is a naming convention within the project, I will follow it.

Comment (gronxb) [reply packages/react-native/src/integrations/console.ts:3]: `__bridge_debug_injected_{randomId}` 👍

**Comment by wogns3623** [comment]
Here you go 😉

**Review by gronxb — APPROVED** [review]

**Comment by gronxb** [comment]
Thanks !!
